### ISSUE TITLE
手机issue

### ISSUE THREAD

**Issue by zhuhuiwen** [zhuhuiwen/vaxunissue#1]
1. input默认在手机上有圆角去除  (2017-05-23)
```css
    input[type="button"] ，textarea{
        -webkit-appearance: none;
        border-radius: 0;
    }
```
